from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class PlanRequest(BaseModel):
    request: str = Field(
        ...,
        description="Natural language trip request",
        json_schema_extra={"example": "5 day trip to Tokyo and Kyoto with $3000 budget focusing on food and temples"}
    )

class HealthResponse(BaseModel):
    status: str = "ok"
    service: str = "ai-travel-planner-backend"

class PlanStubResponse(BaseModel):
    trace_id: str
    status: str = "stub_completed"
    request: str
    constraints_summary: Dict[str, Any] = Field(
        default_factory=lambda: {
            "destination_region": "Japan (Stub)",
            "cities": ["Tokyo", "Kyoto"],
            "duration_days": 5,
            "budget_total": 3000,
            "currency": "USD"
        }
    )
    itinerary_stub: List[Dict[str, Any]] = Field(
        default_factory=lambda: [
            {"day": 1, "city": "Tokyo", "summary": "Arrival & Shibuya Exploration"},
            {"day": 2, "city": "Tokyo", "summary": "Asakusa Temples & Tsukiji Outer Market"},
            {"day": 3, "city": "Kyoto", "summary": "Shinkansen to Kyoto & Gion Evening Walk"},
            {"day": 4, "city": "Kyoto", "summary": "Fushimi Inari & Arashiyama Bamboo Grove"},
            {"day": 5, "city": "Kyoto", "summary": "Souvenir Shopping & Departure"}
        ]
    )
    disclaimer: str = (
        "This itinerary is an illustrative demonstration generated by AI Travel Planner stub system. "
        "Logistics, pricing, and bookings are not guaranteed real-time inventory."
    )


class PlanDraftResponse(BaseModel):
    trace_id: str
    status: str = "draft_completed"
    request: str
    draft_itinerary: Dict[str, Any]
    disclaimer: str = (
        "This itinerary is an illustrative demonstration generated by AI Travel Planner multi-agent system. "
        "Logistics, pricing, and bookings are not guaranteed real-time inventory."
    )


class PlanFinalResponse(BaseModel):
    trace_id: str
    status: str = "plan_completed"
    request: str
    final_itinerary: Dict[str, Any]
    disclaimer: str = (
        "This itinerary is an illustrative demonstration generated by AI Travel Planner multi-agent system. "
        "Logistics, pricing, and bookings are not guaranteed real-time inventory."
    )


